version: 2
updates:
- package-ecosystem: nuget
  directory: "/src/PSTui/"
  schedule:
    interval: weekly
- package-ecosystem: nuget
  directory: "/src/PSTui.Models/"
  schedule:
    interval: weekly
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
